### GET FEED
GET http://localhost:4004/agenda/sessions?$expand=TOPICS,FILES&$orderby=DATE%20desc
Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=BF0500A09E25F74B1700241A45A38215C00500A09E25F74B1700241A45A38215C10500A09E25F74B1700241A45A38215C20500A09E25F74B1700241A45A38215

### POST SESSIONS
POST http://localhost:4004/agenda/sessions
Content-Type: application/json
Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=B9480080F702A14B1700B616AE299581BA480080F702A14B1700B616AE299581BB480080F702A14B1700B616AE299581BC480080F702A14B1700B616AE299581

{
    "DATE": "2020-10-01",
    "TITLE": "HANA Forum",
    "DESC": "This session is on performance in HANA",
    "TOPICS": [
        {
            "USER_EMAIL": "krishnan.gautam@in.bosch.com",
            "SUB_TOPIC": "Union Node Pruning"
        }
    ]
}


### GET OTP
GET http://localhost:3330/user/auth/otp?user=Gomzi


### POST LOGIN
POST http://localhost:3330/user/auth/login
Content-Type: application/json

{
    "user": "Gomzi",
    "otp": 782367
}


### POST SIGNUP
POST http://localhost:3330/user/signup
Content-Type: application/json

{
    "email": "kattapratheek.reddy@in.bosch.com",
    "idno": "33447890",
    "name": "Katta Reddy",
    "ntid": "TKT2KOR",
    "dept": "RBEI/BSL7",
    "username": "Katta"
}

### POST ADMIN-APPROVAL
POST http://localhost:3330/admin/approve
Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=B9480080F702A14B1700B616AE299581BA480080F702A14B1700B616AE299581BB480080F702A14B1700B616AE299581BC480080F702A14B1700B616AE299581
Content-Type: application/json

{
    "email" : "pratheekreddy.katta@in.bosch.com",
    "status" : "A"
}


### GET READ PROFILE
GET http://localhost:4004/profile/readprofile(email='krishnan.gautam@in.bosch.com')/Set
# Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFTUFJTF9JRCI6ImtyaXNobmFuLmdhdXRhbUBpbi5ib3NjaC5jb20iLCJleHAiOjE1OTk1ODExOTMsImlhdCI6MTU5OTUzNzk5M30._8965BSXC43thZU6O0qE8omxByzlHmqrDDuOJMtgDqU

### PUT UPDATE PROFILE
PATCH http://localhost:4004/profile/updateprofile('krishnan.gautam@in.bosch.com')
Content-Type: application/json
# Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFTUFJTF9JRCI6ImtyaXNobmFuLmdhdXRhbUBpbi5ib3NjaC5jb20iLCJleHAiOjE1OTk1ODExOTMsImlhdCI6MTU5OTUzNzk5M30._8965BSXC43thZU6O0qE8omxByzlHmqrDDuOJMtgDqU

{
    "DEPT": "RBEI/BSL5"
}
### GET USER APPROVE LIST
GET http://localhost:4004/userapproval/user_list?$orderby=REGD_ON
# Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFTUFJTF9JRCI6ImtyaXNobmFuLmdhdXRhbUBpbi5ib3NjaC5jb20iLCJleHAiOjE1OTk1ODExOTMsImlhdCI6MTU5OTUzNzk5M30._8965BSXC43thZU6O0qE8omxByzlHmqrDDuOJMtgDqU

### GET VALID USERNAME
GET http://localhost:3330/user/valid?username=Lacchi
# Authorization: requester=krishnan.gautam@in.bosch.com;rbei_access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFTUFJTF9JRCI6ImtyaXNobmFuLmdhdXRhbUBpbi5ib3NjaC5jb20iLCJleHAiOjE1OTk1ODExOTMsImlhdCI6MTU5OTUzNzk5M30._8965BSXC43thZU6O0qE8omxByzlHmqrDDuOJMtgDqU


### LOGOUT
